# This is a basic workflow to help you get started with Actions

name: cron-monthly

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '0 15 28-31 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Runs a single command using the runners shell
    - name: rm monthly
      run: /usr/bin/test $(date -d '+1 day' +%d) -eq 1 && rm ./json/monthly.json 

