name: cron-deploy

on:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: |
        python update_jsons.py
        python update_html.py
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_DIR: ./json
          PUBLISH_BRANCH: master 
          KEEP_FILES: true
